### PR TITLE
Add reveal animation for API > 21

### PR DESCRIPTION
**Pull request by lgvalle**
Add new revel animation on AnimationUtils for devices with API level >= 21

### CODE REVIEW

**Comment by ffgiraldez** [comment]
could be great update the gif in README.md with both animations :P

**Comment by lgvalle** [comment]
Here it is a screenshot and I'll let @MiguelCatalan deal with the README :)

search-reveal

**Comment by MiguelCatalan** [comment]
I will include it as optional feature, probably in the next release (asap). And of course I will add some gif examples :santa:

**Comment by MiguelCatalan** [comment]
On hold due to a small performance issue

**Pull request merged**
